version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports: 
      - '5432:5432'
    volumes:
      - notes-db:/var/lib/postgresql/data
  server:
    build:
      context: ./server
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - '8080:8080'
  client:
    build:
      context: ./client
    expose:
        - 3000
    ports:
        - 3000:3000
    volumes:
        - ./client/src:/usr/src/app/src
        - ./client/public:/usr/src/app/public
    links:
        - "server:server"
    depends_on: 
        - server

volumes:
  notes-db: